const SCREEN_WIDTH = 400
const SCREEN_HEIGHT = 240
const WORLD_WIDTH = SCREEN_WIDTH * 20
const TILE_SIZE = 16
const MAX_HEALTH = 5

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  WORLD_WIDTH,
  MAX_HEALTH,
  TILE_SIZE
}
